### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by flying4fun** [famzah/rrd-json-grafana-ds#1]
`PHP` Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /.../html/rrd-json-grafana-ds/vendor/famzah/PNP/PNPApp.php on line 84`

I get this in the httpd error login when I attempt the following command:

curl --data '{"target": ""}' --user admin  "https://mydomain.com/rrd-json-grafana-ds/search"

ideas on what the problem might be?

php -v
PHP 5.4.40 (cli) (built: Aug 30 2016 13:52:21) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by famzah** [comment]
Hi. This has been tested with PHP 7.0. I don't think it can work with PHP 5.4.

**Comment by famzah** [comment]
I just saw that there are some commits stating "PHP 5.6 compatibility fixes". Made by me :) So PHP 5.6 should be the minimum.

**Comment by flying4fun** [comment]
Thanks.  That really is an old version of PHP.  I've upgraded it and no longer get that error.
